const NavigationRoutes = {
  DRAWER_NAVIGATION: 'drawer',
  SPLASH_SCREEN: 'splashScreen',
  WELCOME_SCREEN: 'WelcomeScreen',
  SIGN_UP_SCREEN: 'SignUpScreen',
  SIGN_IN_SCREEN: 'SignINScreen',
  OTP_SCREEN: 'OTPScreen',
  PERSONAL_SCREEN: 'PersonalScreen',
  CONTACT_SCREEN: 'ContactScreen',
  EDUCATION_SCREEN: 'EducationScreen',
  RESIDENT_SCREEN: 'ResidentScreen',
  PROFESSION_SCREEN: 'ProfessionScreen',
  SOCIAL_SCREEN: 'SocialScreen',
  PROFILE_SCREEN: 'ProfileScreen',
  FORGET_SCREEN: 'ForgetScreen',
  ACCOUNT_SELECTION_SCREEN: 'AccountSelectionScreen',
  CHANGE_PASS_SCREEN: 'ChangePassScreen',
  REFERRAL_SCREEN: 'referralCodeScreen',
  ADD_POST_SCREEN: 'AddPostScreen',
  TIMELINE: 'Timeline',
  GALLERY: 'Gallery',
  DETAILS: 'Details',
  INVITE_SCREEN: 'InviteScreen',
  LIVE: 'Live',
  RESIDENT: 'Residence',
  OFFICE: 'Office',
  ABOUT_SCREEN: 'AboutUsScreen',
  WEBVIEW_SCREEN: 'Privacy Policy and Terms',
};
export default NavigationRoutes;
