const FontSizes = {
  FONT_SIZE_TERMS: 10,
  FONT_SIZE_EXTRA_SMALL: 12,
  FONT_SIZE_SMALL: 14,
  FONT_SIZE_DEFAULT: 16,
  FONT_SIZE_MEDIUM: 18,
  FONT_SIZE_EXTRA_MEDIUM: 20,
  FONT_SIZE_MEDIUM_LARGE: 22,
  FONT_SIZE_LARGE: 24,
  FONT_SIZE_XL: 26,
  FONT_SIZE_XXL: 28,
  FONT_SIZE_XXXL: 30,
  FONT_SIZE_SUPREME: 32,
  FONT_SIZE_EXTRA_SUPREME: 35,
  FONT_SIZE_EXTRA_MEDIUM_SUPREME: 40,
  FONT_SIZE_EXTRA_EXTRA_SUPREME: 80,
};

export default FontSizes;
